name: Run Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test with Go
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16

      - name: Run Tests
        run: |
          go test

      - name: Run Submodule Tests
        run: |
          go test github.com/dasginganinja/drush-launcher/drushlauncher
